### PR TITLE
First pass at widget code improvements

### PR DESCRIPTION
**Pull request by GaryJones**
- New widgets.php file introduced which contains the code that causes
  effects (registers widgets), leaving the existing files to be renamed as
  pure class files.
- Redundant widget registration functions formally deprecated.
- Widget setting defaults consistently moved into constructor for easier
  identification.
- Fixed un-internationalized strings.
- More adherence to code standards.
- Some double-quoted strings changed to single-quoted strings.
- Cleaner and moe consistent coding style, making code easier to read.
- Files, classes, methods and functions all documented.
- Type-hinting added for array parameters.
- More appropriate sanitization for numerical fields.
- Escaping added for some attributes.
- Use of selected() where appropriate.
- A few todo comments left as reminders for later passes of the code.
- Version added to enqueued resource so cache can be automaticalled busted.
- Removed PHP4 constructor naming.

Note, that this code has not been tested, due to not having SB setup ready to run - it may need merging, then some debugging for anything I've missed.

### CODE REVIEW

**Comment by GaryJones** [comment]
You didn't like the changes?

**Comment by brichards** [comment]
I DID, actually! We're merging them into the 3.0 branch starting next week as we begin our comprehensive refactoring.

Haven't seen you in the #wpstartbox channel since you submitted this to make you aware of the plan :)

**Comment by GaryJones** [comment]
A note with the closing of the PR would have been fine ;-)

**Comment by brichards** [comment]
OH, GitHub must have automatically closed this on my behalf when I was merging 2.7 into master. Bah, I didn't even notice.

**Comment by brichards** [comment]
I've merged your changes into the 2.7.2 branch. They're really really stellar, thanks again!

I wasn't ready to commit to the new file name convention you suggested, so I renamed the files back to their original format, but I fully support everything else. Cheers!

**Comment by GaryJones** [comment]
You're welcome :-)

**Pull request closed without merging**
